### ISSUE TITLE
question about default configuration

### ISSUE THREAD

**Issue by peow** [skywardmc/threadtweak#10]
the default configuration of Smooth Boot and ThreadTweaks are different, why? the default configurations of threadtweak are better?

https://github.com/UltimateBoomer/mc-smoothboot/wiki/Configuration~-Fabric-1.16+

**Comment by intergrav** [comment]
The default configurations of ThreadTweak and Smooth Boot (as of right now) are not different in any way, both are as follows:
```json
{
  "threadCount": {
    "bootstrap": 1,
    "main": 11
  },
  "threadPriority": {
    "game": 5,
    "bootstrap": 1,
    "main": 1,
    "io": 1,
    "integratedServer": 5
  }
}
```
I assume that wiki page is out of date.
