### ISSUE TITLE
Just Thank

### ISSUE THREAD

**Issue by Chocotea92** [skywardmc/threadtweak#13]
Good evening. I just want to say a human thank you and shake hands for this modification. Before that, I had to play on my own local Paper server to avoid "freezes" when generating chunks. I don't have a completely bad hardware, but the processor remained i5-6400, and this is a weak point that did not cope well with the game. With your modification, I can play single-player survival as comfortably as on the Paper server, but still pause the game. Thanks Please do not stop working on this modification. I wish you to achieve popularity so that as many players as possible enjoy the modern versions!

**Comment by intergrav** [comment]
👍👍👍
