### ISSUE TITLE
Not an issue, but a question about Sinytra Connector

### ISSUE THREAD

**Issue by ElenaNya** [skywardmc/threadtweak#20]
Managed to start with Sinytra Connector, and now the question arise, in your opinion, is there any sense to use Smooth boot (Reloaded)? What would be better to use for Forge?

Minecraft: 1.20.1
Forge: 47.2.30

**Comment by getchoo** [comment]
> is there any sense to use Smooth boot (Reloaded)?

From a quick look, it seems neither have changed much compared to the original Smooth Boot. This should mean we have similar performance benefits -- assuming Sinytra doesn't introduce overhead (I don't imagine it does)

> What would be better to use for Forge?

I can't answer this for sure though, as I am not a Forge user and I haven't installed Smooth Boot Reloaded before. So, I can only recommend using whichever you find performs better on your system; if they perform the same, it's really just up to your preference :)

If you or others have questions, feel free to re-open. Closing in the meantime
P.S. sorry for the long wait in response 🫠

**Comment by Krimatoria** [comment]
without a mod
![Image](https://github.com/user-attachments/assets/18b9efb5-1ceb-4967-8da3-70b9915eb8c8)
I tried adding it via the connector, maybe if it was on Forge sometime, the performance would be better, but with the addition of the avg mod, it increased.
![Image](https://github.com/user-attachments/assets/7631f319-e950-4950-95b8-643c97ddcd52)
with the mod
