### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by ghost** [skywardmc/threadtweak#21]
Update for 1.21?

**Comment by jschenke488** [comment]
In my limited testing, no changes need to be made except for updating the Minecraft version in fabric.mod.json. A temporary solution if somebody needs this mod would be adding a dependency override (see https://fabricmc.net/wiki/tutorial:dependency_overrides).
https://github.com/skywardmc/threadtweak/blob/202598bf0934e4bbe21751439e3a30014e97d6cd/src/main/resources/fabric.mod.json#L26

**Comment by sternschnaube** [comment]
Thanks for testing out @jschenke488.

**Comment by tajemniktv** [comment]
Might be a better alternative; https://modrinth.com/mod/stutterfix
