### ISSUE TITLE
Conflict with Iris Shaders 1.6.10

### ISSUE THREAD

**Issue by RoonMoonlight** [skywardmc/threadtweak#8]
Hello, after updating Iris Shaders 1.6.10 on my modpack, it seems your ThreadTweak mod is conflicting with Iris, since there is `com.github.getchoo.smoothboot.mixin.client.MainMixin (smoothboot.mixins.json)` on Mixin Trace. Would be grateful if you could look what happened.

Crash Report:
https://mclo.gs/K0lQqVH

Thanks

**Comment by Phoenix-Starlight** [comment]
No it is not threadtweak, try again with a new instance. In fact, your crash report **has no** mention of it.

**Comment by RoonMoonlight** [comment]
> No it is not threadtweak, try again with a new instance. In fact, your crash report **has no** mention of it.

Look at the **com.github.getchoo.smoothboot.mixin.client.MainMixin (smoothboot.mixins.json** mention again on crash report

**Comment by RoonMoonlight** [comment]
Smooth Boot = ThreadTweaks

**Comment by uku3lig** [comment]
while i am sure it's not a threadtweak issue, i can at the very least provide some insight on the problem.

the mod causing the issue here is indium. it's trying to access something that for some unknown (and probably extremely cursed) reason isn't here (intermediary mappings).

the reason why you're seeing threadtweak and modernfix (among other mods) is because they mixin into some essential classes of minecraft, namely `Main` and `MinecraftClient` (which, due to being used to literally launch the game, will _almost_ always show up in stack traces).

so, according to what you said about updating iris to 1.6.10, while unlikely it seems possible that it could be the issue.

**Comment by RoonMoonlight** [comment]
This is weird, Fabulously Optimized works even that mod has Iris updated... I can see some Prism Launcher on error log, I will try using Modrinth App instead (as that launcher worked like a charm before)

**Comment by uku3lig** [comment]
> I can see some Prism Launcher on error log

that's because you're using prism launcher. it is not the cause of the error.

**Comment by MenacingPerson** [comment]
Try removing fabric loader and adding it again. @RoonMoonlight

**Comment by RoonMoonlight** [comment]
> while i am sure it's not a threadtweak issue, i can at the very least provide some insight on the problem.
> 
> the mod causing the issue here is indium. it's trying to access something that for some unknown (and probably extremely cursed) reason isn't here (intermediary mappings).
> 
> the reason why you're seeing threadtweak and modernfix (among other mods) is because they mixin into some essential classes of minecraft, namely `Main` and `MinecraftClient` (which, due to being used to literally launch the game, will _almost_ always show up in stack traces).
> 
> so, according to what you said about updating iris to 1.6.10, while unlikely it seems possible that it could be the issue.

Okay I will forward this to Indium repo

**Comment by uku3lig** [comment]
please try what i suggested first, downgrading iris and/or fabric loader. please don't bother other mod devs until you're 100% sure it comes from their mod

**Comment by RoonMoonlight** [comment]
> please try what i suggested first, downgrading iris and/or fabric loader. please don't bother other mod devs until you're 100% sure it comes from their mod

**Because I don't even KNOW WHERE TO GET SOLUTIONS.** I am modpack dev and I need this to be addressed first to get it released

**Comment by RoonMoonlight** [comment]
Geez no one is actually trying to be helpful...

**Comment by uku3lig** [comment]
have you tried what i said? and if yes, did it fix your issues?

**Comment by intergrav** [comment]
> Geez no one is actually trying to be helpful...

Friendly reminder not to say this kind of stuff. Doing this will only make the people who are helping you not want to continue helping.
